//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSSAppApi.ChannelService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Channel", Namespace="http://schemas.datacontract.org/2004/07/RSSBackgroundWorkerBusinessWCF.Messages")]
    [System.SerializableAttribute()]
    public partial class Channel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSAppApi.ChannelService.Article[] ArticlesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSAppApi.ChannelService.Channel.Image ChannelImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RSS_URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSAppApi.ChannelService.Article[] Articles {
            get {
                return this.ArticlesField;
            }
            set {
                if ((object.ReferenceEquals(this.ArticlesField, value) != true)) {
                    this.ArticlesField = value;
                    this.RaisePropertyChanged("Articles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSAppApi.ChannelService.Channel.Image ChannelImage {
            get {
                return this.ChannelImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ChannelImageField, value) != true)) {
                    this.ChannelImageField = value;
                    this.RaisePropertyChanged("ChannelImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RSS_URL {
            get {
                return this.RSS_URLField;
            }
            set {
                if ((object.ReferenceEquals(this.RSS_URLField, value) != true)) {
                    this.RSS_URLField = value;
                    this.RaisePropertyChanged("RSS_URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Channel.Image", Namespace="http://schemas.datacontract.org/2004/07/RSSBackgroundWorkerBusinessWCF.Messages")]
        [System.SerializableAttribute()]
        public partial class Image : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string TitleField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string URLField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Title {
                get {
                    return this.TitleField;
                }
                set {
                    if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                        this.TitleField = value;
                        this.RaisePropertyChanged("Title");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string URL {
                get {
                    return this.URLField;
                }
                set {
                    if ((object.ReferenceEquals(this.URLField, value) != true)) {
                        this.URLField = value;
                        this.RaisePropertyChanged("URL");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Article", Namespace="http://schemas.datacontract.org/2004/07/RSSBackgroundWorkerBusinessWCF.Messages")]
    [System.SerializableAttribute()]
    public partial class Article : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChannelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PubDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChannelId {
            get {
                return this.ChannelIdField;
            }
            set {
                if ((this.ChannelIdField.Equals(value) != true)) {
                    this.ChannelIdField = value;
                    this.RaisePropertyChanged("ChannelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PubDate {
            get {
                return this.PubDateField;
            }
            set {
                if ((this.PubDateField.Equals(value) != true)) {
                    this.PubDateField = value;
                    this.RaisePropertyChanged("PubDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChannelMessage", Namespace="http://schemas.datacontract.org/2004/07/RSSBackgroundWorkerBusinessWCF.Messages")]
    [System.SerializableAttribute()]
    public partial class ChannelMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Exception ExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSAppApi.ChannelService.Channel MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSAppApi.ChannelService.MessageStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception Exception {
            get {
                return this.ExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionField, value) != true)) {
                    this.ExceptionField = value;
                    this.RaisePropertyChanged("Exception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSAppApi.ChannelService.Channel Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSAppApi.ChannelService.MessageStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageStatus", Namespace="http://schemas.datacontract.org/2004/07/RSSBackgroundWorkerBusinessWCF.Messages")]
    public enum MessageStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Created = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Updated = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NothingModified = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChannelService.IChannelService")]
    public interface IChannelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChannelService/GetChannels", ReplyAction="http://tempuri.org/IChannelService/GetChannelsResponse")]
        RSSAppApi.ChannelService.Channel[] GetChannels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChannelService/GetChannels", ReplyAction="http://tempuri.org/IChannelService/GetChannelsResponse")]
        System.Threading.Tasks.Task<RSSAppApi.ChannelService.Channel[]> GetChannelsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChannelService/GetChannel", ReplyAction="http://tempuri.org/IChannelService/GetChannelResponse")]
        RSSAppApi.ChannelService.Channel GetChannel(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChannelService/GetChannel", ReplyAction="http://tempuri.org/IChannelService/GetChannelResponse")]
        System.Threading.Tasks.Task<RSSAppApi.ChannelService.Channel> GetChannelAsync(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChannelService/AddChannel", ReplyAction="http://tempuri.org/IChannelService/AddChannelResponse")]
        RSSAppApi.ChannelService.ChannelMessage AddChannel(RSSAppApi.ChannelService.Channel channel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChannelService/AddChannel", ReplyAction="http://tempuri.org/IChannelService/AddChannelResponse")]
        System.Threading.Tasks.Task<RSSAppApi.ChannelService.ChannelMessage> AddChannelAsync(RSSAppApi.ChannelService.Channel channel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChannelService/UpdateChannel", ReplyAction="http://tempuri.org/IChannelService/UpdateChannelResponse")]
        RSSAppApi.ChannelService.ChannelMessage UpdateChannel(RSSAppApi.ChannelService.Channel channel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChannelService/UpdateChannel", ReplyAction="http://tempuri.org/IChannelService/UpdateChannelResponse")]
        System.Threading.Tasks.Task<RSSAppApi.ChannelService.ChannelMessage> UpdateChannelAsync(RSSAppApi.ChannelService.Channel channel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChannelService/DeleteChannel", ReplyAction="http://tempuri.org/IChannelService/DeleteChannelResponse")]
        RSSAppApi.ChannelService.ChannelMessage DeleteChannel(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChannelService/DeleteChannel", ReplyAction="http://tempuri.org/IChannelService/DeleteChannelResponse")]
        System.Threading.Tasks.Task<RSSAppApi.ChannelService.ChannelMessage> DeleteChannelAsync(string url);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChannelServiceChannel : RSSAppApi.ChannelService.IChannelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChannelServiceClient : System.ServiceModel.ClientBase<RSSAppApi.ChannelService.IChannelService>, RSSAppApi.ChannelService.IChannelService {
        
        public ChannelServiceClient() {
        }
        
        public ChannelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChannelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChannelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChannelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RSSAppApi.ChannelService.Channel[] GetChannels() {
            return base.Channel.GetChannels();
        }
        
        public System.Threading.Tasks.Task<RSSAppApi.ChannelService.Channel[]> GetChannelsAsync() {
            return base.Channel.GetChannelsAsync();
        }
        
        public RSSAppApi.ChannelService.Channel GetChannel(string url) {
            return base.Channel.GetChannel(url);
        }
        
        public System.Threading.Tasks.Task<RSSAppApi.ChannelService.Channel> GetChannelAsync(string url) {
            return base.Channel.GetChannelAsync(url);
        }
        
        public RSSAppApi.ChannelService.ChannelMessage AddChannel(RSSAppApi.ChannelService.Channel channel) {
            return base.Channel.AddChannel(channel);
        }
        
        public System.Threading.Tasks.Task<RSSAppApi.ChannelService.ChannelMessage> AddChannelAsync(RSSAppApi.ChannelService.Channel channel) {
            return base.Channel.AddChannelAsync(channel);
        }
        
        public RSSAppApi.ChannelService.ChannelMessage UpdateChannel(RSSAppApi.ChannelService.Channel channel) {
            return base.Channel.UpdateChannel(channel);
        }
        
        public System.Threading.Tasks.Task<RSSAppApi.ChannelService.ChannelMessage> UpdateChannelAsync(RSSAppApi.ChannelService.Channel channel) {
            return base.Channel.UpdateChannelAsync(channel);
        }
        
        public RSSAppApi.ChannelService.ChannelMessage DeleteChannel(string url) {
            return base.Channel.DeleteChannel(url);
        }
        
        public System.Threading.Tasks.Task<RSSAppApi.ChannelService.ChannelMessage> DeleteChannelAsync(string url) {
            return base.Channel.DeleteChannelAsync(url);
        }
    }
}
